[project]

name = "nws-weather"

version = "0.0.2"

description = "NWS Weather Client"

dependencies = [
    "requests>=2"
]

[project.scripts]
nws = "nws_weather.cli:main"

[tool.setuptools]
packages = ["nws_weather"]
